### ISSUE TITLE
SyntaxError on load

### ISSUE THREAD

**Issue by silascutler** [ChiChou/IDA-ObjCExplorer#1]
Hello @ChiChou ,

On IDA 7.4 with Python 2.7, the plugin fails to load with the following error.  

```
/home/analysis/.idapro/plugins/ocexplorer.py: invalid syntax (ocexplorer.py, line 133)
Traceback (most recent call last):
  File "/opt/idapro/idapro-7.4/python/2/ida_idaapi.py", line 618, in IDAPython_ExecScript
    code = compile(fin.read(), script, 'exec')
  File "/home/analysis/.idapro/plugins/ocexplorer.py", line 133
    def print(self, *args):
            ^
SyntaxError: invalid syntax

```

I'm found a temporary work around is to 

```
-    def rprint(self, *args):
+    def rprint(self, *args):

and replace comment out all print statements. 

```
I'll work on a fork for Python 2.7 and submit it once I have it working

(Specific IDA version)
```
Python 2.7.17 (default, Jul 20 2020, 15:37:01) 
[GCC 7.5.0] 
IDAPython 64-bit v7.4.0 final (serial 0) (c) The IDAPython Team <idapython@googlegroups.com>
```

**Comment by ChiChou** [comment]
Sorry python2 is not intended to be supported.
https://www.python.org/doc/sunset-python-2/

I've got more ideas to implement, supporting python2 will slow down the development

**Comment by silascutler** [comment]
Sounds good.  Thanks
